// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhQ9mezCuCTGqbOY3JQG1_O9Ld9QBChIQ',
    appId: '1:527468326707:web:3a55a55402a384acafd846',
    messagingSenderId: '527468326707',
    projectId: 'tpappmobile-eabde',
    authDomain: 'tpappmobile-eabde.firebaseapp.com',
    storageBucket: 'tpappmobile-eabde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhTOBoLl_hSPRdu8-pjYtol3MRC0kmwoE',
    appId: '1:527468326707:android:154b9f569b4c90acafd846',
    messagingSenderId: '527468326707',
    projectId: 'tpappmobile-eabde',
    storageBucket: 'tpappmobile-eabde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rUr0EILBtmKrWJdXQFyAWTqS42ZEajo',
    appId: '1:527468326707:ios:6c63c2112d2ebd02afd846',
    messagingSenderId: '527468326707',
    projectId: 'tpappmobile-eabde',
    storageBucket: 'tpappmobile-eabde.appspot.com',
    iosBundleId: 'com.example.tp',
  );
}
